### ISSUE TITLE
Jupiterone no longer in Pypi

### ISSUE THREAD

**Issue by sdzharkov** [JupiterOne/jupiterone-api-client-python#18]
Hey team - was the whole package removed from pypi? https://pypi.org/project/jupiterone/ is showing a "page not found" error. I am no longer able to run `pip install jupiterone`

**Comment by SeaBlooms** [comment]
we're working on publishing 1.0.0 to pypi now, thanks for raising

**Comment by SeaBlooms** [comment]
https://pypi.org/project/jupiterone/1.0.0/ this has been fixed, we will continue to maintain and more incremental improvements
