### ISSUE TITLE
No version tag in this repo?

### ISSUE THREAD

**Issue by TiansuYu** [JupiterOne/jupiterone-api-client-python#22]
Where no version tags in this repo? How should one check quickly between version changes?

**Comment by SeaBlooms** [comment]
added 1.0.0 tag/release - https://github.com/JupiterOne/jupiterone-api-client-python/releases/tag/v1.0.1

let me know if you have any questions

**Comment by SeaBlooms** [comment]
also here: https://pypi.org/project/jupiterone/#history

**Comment by TiansuYu** [comment]
Thanks for adding tags, as a library, it is always nice to have the tags in git history, as someone walks in can quickly checkout different versions.
